"""
config.py — Central project configuration
==========================================
Edit only this file to configure the entire pipeline.
All other scripts import from here.

Project: diesel-emissions-pipeline
"""

import os
from pathlib import Path

# ─── GCP Credentials ──────────────────────────────────────────────────────────
# Full path to your Service Account JSON key file.
# Example Windows: C:\\keys\\whsc-homologacao-sa.json
CREDENTIALS_PATH = r"C:\Aula\Aula+Python\secret\whsc-homologacao-bad620c810f0.json"

# ─── GCP Project ──────────────────────────────────────────────────────────────
GCP_PROJECT_ID  = "whsc-homologacao"
DATASET_REGION  = "US"

# ─── GCS ──────────────────────────────────────────────────────────────────────
GCS_BUCKET_NAME = "whsc-homolo"
GCS_RAW_PREFIX  = "raw/dyno_emissions"         # folder structure inside bucket

# ─── BigQuery ─────────────────────────────────────────────────────────────────
BQ_DATASET_RAW  = "diesel_raw"                 # bronze layer
BQ_TABLE_RAW    = "dyno_measurements"

# ─── Local paths ──────────────────────────────────────────────────────────────
LOCAL_CSV_PATH  = "dyno_emissions_data.csv"    # generated by generate_dyno_data.py

# ─── Derived values (do not edit) ─────────────────────────────────────────────
GCS_CSV_URI     = f"gs://{GCS_BUCKET_NAME}/{LOCAL_CSV_PATH}"
BQ_FULL_TABLE   = f"{GCP_PROJECT_ID}.{BQ_DATASET_RAW}.{BQ_TABLE_RAW}"


def validate():
    """Check that the credentials file exists before running any script."""
    creds = Path(CREDENTIALS_PATH)
    if not creds.exists():
        raise FileNotFoundError(
            f"\nCredentials file not found: {CREDENTIALS_PATH}\n"
            f"Steps to fix:\n"
            f"  1. Go to GCP Console → IAM & Admin → Service Accounts\n"
            f"  2. Create a Service Account with roles:\n"
            f"       - Storage Object Admin\n"
            f"       - BigQuery Data Editor\n"
            f"       - BigQuery Job User\n"
            f"  3. Create a JSON key and save it to: {CREDENTIALS_PATH}\n"
        )
    print(f"Credentials OK: {CREDENTIALS_PATH}")
    return str(creds)
